project:
  type: website
  output-dir: _site

website:
  title: "Intro252"
  navbar:
    left:
      - text: Sessions
        menu:
          - text: 01 — Introduction
            href: sessions/01_intro/index.qmd
          - text: 02 – Pragmatics
            href: sessions/02_pragmatics/index.qmd
          - text: 03 – Phonetics
            href: sessions/03_phonetics/index.qmd
          - text: 04 – Phonology
            href: sessions/04_phonology/index.qmd
          - text: 05 — Syntax I
            href: sessions/05_syntax/index.qmd
          - text: 06 — Syntax II
            href: sessions/05_syntax/index.qmd

format:
  html:
    theme: cosmo
    toc: true
    css: custom.css
filters:
  - auto-dark

bibliography: references.bib

# Project-wide metadata (available via {{< meta name >}})
metadata:
  linkprefix: ""

params:
  show_solutions: false