project:
  type: website
  output-dir: _site

website:
  title: "Intro252"
  navbar:
    left:
      - text: Sessions
        menu:
          - text: Session 01 — Introduction
            href: sessions/01_intro/index.qmd

format:
  html:
    theme: cosmo
    toc: true
    css: custom.css
filters:
  - auto-dark

bibliography: references.bib