project:
  type: website
  output-dir: _site

website:
  title: "Introduction to linguistics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Sessions
        menu:
          - text: Session 01 — Introduction
            href: sessions/01_intro/slides.qmd

format:
  html:
    theme: cosmo
    toc: true
    css: custom.css

bibliography: references.bib


